### ISSUE TITLE
422 error when submitting profile information

### ISSUE THREAD

**Issue by karaluton** [matthewtrask/developerresumes#52]
<img width="596" alt="screen shot 2018-02-26 at 10 27 08 am" src="https://user-images.githubusercontent.com/21015193/36681976-a8b86924-1adf-11e8-9dd3-d772e6071053.png">

**Comment by matthewtrask** [comment]
yea, the issue is I need to validate and enforce the input fields. Thanks for catching this.

**Comment by matthewtrask** [comment]
fixed with a million pr's. @karaluton can you give it a try when you have time?

**Comment by karaluton** [comment]
@matthewtrask worked for me!
